import 'package:church_notes/domain/enums/bible_version.dart';
import 'package:church_notes/domain/enums/language.dart';

class BibleBook {
  final String name;
  const BibleBook._(this.name);

  static List<BibleBook> getNames(BibleVersion version) {
    // switch (version) {
    //   case BibleVersion.asv:
    //     return englishNames;
    //   case BibleVersion.tb:
    //     return indonesianNames;
    // }
    switch (version.language) {
      case Language.english:
        return englishNames;
      case Language.indonesian:
        return indonesianNames;
    }
  }

  static const englishNames = <BibleBook>[
    BibleBook._('Genesis'),
    BibleBook._('Exodus'),
    BibleBook._('Leviticus'),
    BibleBook._('Numbers'),
    BibleBook._('Deuteronomy'),
    BibleBook._('Joshua'),
    BibleBook._('Judges'),
    BibleBook._('Ruth'),
    BibleBook._('1 Samuel'),
    BibleBook._('2 Samuel'),
    BibleBook._('1 Kings'),
    BibleBook._('2 Kings'),
    BibleBook._('1 Chronicles'),
    BibleBook._('2 Chronicles'),
    BibleBook._('Ezra'),
    BibleBook._('Nehemiah'),
    BibleBook._('Esther'),
    BibleBook._('Job'),
    BibleBook._('Psalms'),
    BibleBook._('Proverbs'),
    BibleBook._('Ecclesiastes'),
    BibleBook._('Song of Songs'),
    BibleBook._('Isaiah'),
    BibleBook._('Jeremiah'),
    BibleBook._('Lamentations'),
    BibleBook._('Ezekiel'),
    BibleBook._('Daniel'),
    BibleBook._('Hosea'),
    BibleBook._('Joel'),
    BibleBook._('Amos'),
    BibleBook._('Obadiah'),
    BibleBook._('Jonah'),
    BibleBook._('Micah'),
    BibleBook._('Nahum'),
    BibleBook._('Habakkuk'),
    BibleBook._('Zephaniah'),
    BibleBook._('Haggai'),
    BibleBook._('Zechariah'),
    BibleBook._('Malachi'),
    BibleBook._('Matthew'),
    BibleBook._('Mark'),
    BibleBook._('Luke'),
    BibleBook._('John'),
    BibleBook._('Acts'),
    BibleBook._('Romans'),
    BibleBook._('1 Corinthians'),
    BibleBook._('2 Corinthians'),
    BibleBook._('Galatians'),
    BibleBook._('Ephesians'),
    BibleBook._('Philippians'),
    BibleBook._('Colossians'),
    BibleBook._('1 Thessalonians'),
    BibleBook._('2 Thessalonians'),
    BibleBook._('1 Timothy'),
    BibleBook._('2 Timothy'),
    BibleBook._('Titus'),
    BibleBook._('Philemon'),
    BibleBook._('Hebrews'),
    BibleBook._('James'),
    BibleBook._('1 Peter'),
    BibleBook._('2 Peter'),
    BibleBook._('1 John'),
    BibleBook._('2 John'),
    BibleBook._('3 John'),
    BibleBook._('Jude'),
    BibleBook._('Revelation')
  ];

  static const indonesianNames = <BibleBook>[
    BibleBook._('Kejadian'),
    BibleBook._('Keluaran'),
    BibleBook._('Imamat'),
    BibleBook._('Bilangan'),
    BibleBook._('Ulangan'),
    BibleBook._('Yosua'),
    BibleBook._('Hakim-Hakim'),
    BibleBook._('Rut'),
    BibleBook._('1 Samuel'),
    BibleBook._('2 Samuel'),
    BibleBook._('1 Raja-Raja'),
    BibleBook._('2 Raja-Raja'),
    BibleBook._('1 Tawarikh'),
    BibleBook._('2 Tawarikh'),
    BibleBook._('Ezra'),
    BibleBook._('Nehemia'),
    BibleBook._('Ester'),
    BibleBook._('Ayub'),
    BibleBook._('Mazmur'),
    BibleBook._('Amsal'),
    BibleBook._('Pengkhotbah'),
    BibleBook._('Kidung Agung'),
    BibleBook._('Yesaya'),
    BibleBook._('Yeremia'),
    BibleBook._('Ratapan'),
    BibleBook._('Yehezkiel'),
    BibleBook._('Daniel'),
    BibleBook._('Hosea'),
    BibleBook._('Yoel'),
    BibleBook._('Amos'),
    BibleBook._('Obaja'),
    BibleBook._('Yunus'),
    BibleBook._('Mikha'),
    BibleBook._('Nahum'),
    BibleBook._('Habakuk'),
    BibleBook._('Zefanya'),
    BibleBook._('Hagai'),
    BibleBook._('Zakharia'),
    BibleBook._('Maleakhi'),
    BibleBook._('Matius'),
    BibleBook._('Markus'),
    BibleBook._('Lukas'),
    BibleBook._('Yohanes'),
    BibleBook._('Kisah Para Rasul'),
    BibleBook._('Roma'),
    BibleBook._('1 Korintus'),
    BibleBook._('2 Korintus'),
    BibleBook._('Galatia'),
    BibleBook._('Efesus'),
    BibleBook._('Filipi'),
    BibleBook._('Kolose'),
    BibleBook._('1 Tesalonika'),
    BibleBook._('2 Tesalonika'),
    BibleBook._('1 Timotius'),
    BibleBook._('2 Timotius'),
    BibleBook._('Titus'),
    BibleBook._('Filemon'),
    BibleBook._('Ibrani'),
    BibleBook._('Yakobus'),
    BibleBook._('1 Petrus'),
    BibleBook._('2 Petrus'),
    BibleBook._('1 Yohanes'),
    BibleBook._('2 Yohanes'),
    BibleBook._('3 Yohanes'),
    BibleBook._('Yudas'),
    BibleBook._('Wahyu')
  ];
}
